### ISSUE TITLE
Create wireframe model, add to repo

### ISSUE THREAD

**Issue by SupriyaShekar123** [mitraws/Project-Barangay#3]
Wireframe made using Cacoo tool. A rough sketch for the B&B web page.

[B&B (3).pdf](https://github.com/mitraws/Project-Barangay/files/5311492/B.B.3.pdf)

**Comment by mitraws** [comment]
Looking great! ill go through it more in depth in a moment and let you know if i got any points.

**Comment by SupriyaShekar123** [comment]
Please review and give feedback.

**Comment by mitraws** [comment]
1. I would put "about us" in the end or before contact
2. replace the b&b with the logo 
3. I think its better to replace the login icon at the end of the navbar with the 'show availability' button as they have it on their own site

**Comment by SupriyaShekar123** [comment]
Okay Mitra. I will make the changes and update.

**Comment by SupriyaShekar123** [comment]
All the necessary changes made as suggested by Mitra. Please check and let me know.

**Comment by mitraws** [comment]
Great!

**Comment by mitraws** [comment]
Dont forget to create separate folder: Documents, and add this there in the repo

**Comment by mitraws** [comment]
Wireframe approved by client after update by all of us to match new requirements.
